### ISSUE TITLE
[Bug]: The `__getattr__` method and `@property` decorated functions do not interact well

### ISSUE THREAD

**Issue by JoFrhwld** [Forced-Alignment-and-Vowel-Extraction/alignedTextGrid#188]
### What happened?

in `AlignedTextGrid`, the `__getattr__()` dunder method overrides the return of `@property` decorated functions.

### What operating system are you using?

Mac

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by chrisbrickhouse** [comment]
Do you have a failing test? My guess is that there's an exception being raised in the `@property` function, which causes `__getattribute__` to fallback onto `__getattr__` silently, so you lose the traceback that should actually blame `@property`. If you remove the `__getattr__` function you should get a more helpful traceback.

**Comment by JoFrhwld** [comment]
I had overlooked tests for this, but it's a weirder scenario. There's a `@property` decorated `xmin()` function:

https://github.com/Forced-Alignment-and-Vowel-Extraction/alignedTextGrid/blob/17255f0200efbf8e825a67d2fcc253868c290a32/src/aligned_textgrid/aligned_textgrid.py#L323-L327

But when I try to access it with `atg.xmin`, I get this exception raised by the customized `__getattr__`

https://github.com/Forced-Alignment-and-Vowel-Extraction/alignedTextGrid/blob/17255f0200efbf8e825a67d2fcc253868c290a32/src/aligned_textgrid/aligned_textgrid.py#L127-L128

If I comment out the `__getattr__` method, then `atg.xmin` works without a problem. My guess for now is that somewhere under the hood, `property()` calls `__getattr__`, and so the custom version breaks it.

The special method is there just to provide accessors for tier groups by name, so my plan is to replace `__getattr__` with a private method to add these features using `setattr(self)`, and remove the `__getattr__` method.
